baseURL = "https://nav.r4y.site/"
languageCode = "zh-CN"
title = "CryptoNav导航站"
theme = "webstack-hugo"

preserveTaxonomyNames = true
disablePathToLower = true
hasCJKLanguage = true
copyright = "R4yyy"


[params]
  author = "R4yyy"
  description = "Webstack Hugo"
[params.search]
  enable = false 
[params.darkmode]
  enable = true
[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
